### ISSUE TITLE
Didn't stop drawing when time ran out

### ISSUE THREAD

**Issue by FOBshippingpoint** [FOBshippingpoint/garticio_selenium#1]
I need this cool feature.
I can't even press stop button on a jupyter notebook when pynput is controlling my mouse(even use my keyboard).

**Comment by FOBshippingpoint** [comment]
I think we can detect if the user can draw each line/segment draw. Stop drawing if user's time ran out.
Or make a GUI for this project?

**Comment by elmerchou** [comment]
I would like to make a GUI.
